### ISSUE TITLE
Sci / day amount not updating when reset

### ISSUE THREAD

**Issue by aw94** [magico13/KCT#44] opened 2015-02-11 02:23 UTC
Minor graphical glitch if anything, but if you put upgrade points into tech node research rates, then later reset upgrades, the current sci/day value and the increase amount doesn't change until you click the development upgrade button again.

Also, sort-of-not-really a bug report, since I'd guess this behavior is intended, but is the development upgrade value supposed to be shared across all launch sites (playing RO)? Thought that it was per-launch site like the other upgrades and got really confused when I couldn't upgrade even though I still had upgrade points :(

**Comment by magico13** [comment] 2015-02-11 02:26
Development (tech node unlocks) are a global thing, since the tech itself is global. I'll check that graphical bug out though, thanks!

**Comment by aw94** [comment] 2015-02-11 02:31
Ah, ok, that makes sense. Would it be possible to have some sort of "least upgrade points remaining" indicator then (perhaps in a different issue)?

I'd love to help, but unfortunately I don't know C# or really any of the frameworks behind the mods...

**Comment by aw94** [comment] 2015-02-11 03:06
Hmmm, seems the graphical glitch may be somewhat more pervasive than I originally thought... Seems that if you switch save files, the values (for everything, it seems) that were last displayed from that save are also displayed with the new save, even though the "true" values are normal. Restarting KSP seems to cause everything to return to normal.

**Comment by magico13** [comment] 2015-02-11 03:14
That should get fixed at the same time. The issue is likely that they aren't being reset on scene changes/going to the main menu.

**Comment by aw94** [comment] 2015-02-11 03:28
Oh, ok. Thanks!

**Comment by aw94** [comment] 2015-03-02 03:07
Something I just noticed, but not sure if it's caused by this issue or not. Seems the science researched/day thing isn't just graphical -- KCT treats those values as the actual values until told otherwise.

For example, I had some tech nodes upgrading at full speed, but then reset points to build a vessel, but when I timewarped to vessel completion (few days), turns out the tech node completed along the way, even though it was only ~50% done.

Is that part of this issue?

**Comment by magico13** [comment] 2015-03-02 03:09
> Is that part of this issue?

Most likely. Have you tried with the development builds at all? I'm pretty sure I fixed this by resetting everything on every scene change, but I may have missed a thing or two. I'll double check that the tech nodes are set to recalculate their rates.

**Comment by aw94** [comment] 2015-03-02 03:11
I haven't. I'll go get that, and report back.

**Comment by aw94** [comment] 2015-03-02 15:35
Sorry for the delay; got called away to do chores, then had to go to bed.

The most recent issue does not appear to be fixed in the most recent dev build (#83). The current/next upgrade levels for science researched per day updates ok, but the actual time left to upgrade completion in the upgrade list does not update until you upgrade the development rate.

**Comment by magico13** [comment] 2015-03-02 16:00
Is this when going from an existing save to a brand new save, or when going from an existing save to another existing save, or something else entirely?

Oh crap, I misread what you said earlier/thought we were talking about a slightly different issue. Ok, now that I'm on the right page, I should be able to easily fix this. It should just be one line of code that resets the KCT_GameStates.TotalTechUpgrades back to 0, then forcing all tech nodes to recalculate their build rates.

**Comment by aw94** [comment] 2015-03-02 16:07
This all can take place within the same save, from a newly booted up KSP. 

Glad to hear the fix should be simple, and thank you for your time!

**Comment by magico13** [comment] 2015-03-02 16:34
The fix I did in the dev builds should take care of the issue of going from an existing save to another save though. It should work for going to a new save. I'll need to do some more testing when I fix the other issue tonight.

**Comment by aw94** [comment] 2015-03-02 16:38
Hm. I can't really say much about going between saves; this was more or less all within the same save. It's possible that I missed something though.

**Comment by magico13** [comment] 2015-03-03 02:23
Should be fixed in 84!

**Comment by aw94** [comment] 2015-03-03 04:01
Development rate resets ok both in the upgrade menu and the build list, but now it seems research in the upgrade menu has the problem development used to have :(

Not sure if it affects the amount of science given/86400 BPs, though.

**Comment by magico13** [comment] 2015-03-03 04:21
Thanks for the heads up! I think I've gotten that taken care of now and averted an issue that could arise with it parsing the formula every update if the formula returns 0 (now it only parses it when the stored value is -13, which I doubt anyone will purposefully set the formula to become). It should be in the next dev build.

**Comment by aw94** [comment] 2015-03-03 04:25
All right. I'll be sure to get that when it comes out!

**Comment by aw94** [comment] 2015-03-03 18:16
Alright, the development upgrade/reset seems to be functioning correctly. Only thing is now the development rate starts at 0.01 sci/day in the upgrade window, changes to 0 upon upgrading, and stays like that until upgrades are reset. The 0 appears to be solely cosmetic, since upgrade times in the build list seem to change as expected.

**Comment by magico13** [comment] 2015-03-03 18:33
Looks like I missed one instance of nodeRate = 0, which now needs to be nodeRate = -13. It should be cosmetic, since the tech nodes call the math parser on their own. I might be able to just change that right now through the github website rather than opening visual studio when I get home.

**Closed** 2015-03-25 00:59 UTC
