### ISSUE TITLE
Clicking on VAB after warping to complete does not work

### ISSUE THREAD

**Issue by Aramus92** [magico13/KCT#116] opened 2016-01-25 14:36 UTC
![1](https://cloud.githubusercontent.com/assets/11636684/12553751/6df04a06-c379-11e5-96f9-3d83477e7224.JPG)
![2](https://cloud.githubusercontent.com/assets/11636684/12553752/6e057430-c379-11e5-8b51-ef9f70c12d2e.JPG)
I build a rocket, then I build it, but I cant roll it out. When I click on VAB i just get this strange window in the Screenshot.

**Comment by magico13** [comment] 2016-01-25 16:00
I'll need the log file to have any hope of figuring this out. Are you running RP-0? The screenshots make it look like you're running some sort of system resize and several others have mentioned issues with the RP-0 Preset (which I haven't been able to reproduce in my testing).

**Comment by Aramus92** [comment] 2016-01-25 16:11
RSS with Realism Overhaul and RP-0. What Logfile do you exactly need?

**Comment by magico13** [comment] 2016-01-25 16:17
About halfway down [this post](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/) (also mentioned in the "reporting bugs" section of the KCT forum thread). 

I've got a feeling it's the issue two others were seeing. If it is then the log will mention an error in KCT_MathParsing when trying to parse the Reconditioning Formula.

If you don't mind, could you also upload the save file? Upload the save and the log to dropbox/google drive/any other file storage site. You can .zip them if you want to as it makes the file much smaller.

**Comment by Aramus92** [comment] 2016-01-25 16:20
https://www.dropbox.com/s/7kjsvejlxjlw3go/Log%26Save.rar?dl=0

You were right with KCT_MathParsing, something seems to get negative...

**Comment by magico13** [comment] 2016-01-25 16:28
Alright, thank you for that. I won't be able to attempt any fixes until I get home from work, but I'll hopefully have a fix for this by tomorrow. I'm not sure what it is that's causing this, but it seems to be related only to RP-0 and only for certain setups (when I tested with RP-0 I wasn't having this happen). I'll let you know when I've got something for you to try. Thanks again.

**Comment by magico13** [comment] 2016-01-26 04:10
Somehow KCT is determining the vessel's mass to be negative, which then causes a negative in a square root, which ends up as NaN and then breaks further calculations. I've made it return a minimum of zero so that should take care of that issue. Test out [this .dll](http://magico13.net:8080/job/Kerbal%20Construction%20Time%20Development/189/artifact/Kerbal_Construction_Time/obj/Debug/KerbalConstructionTime.dll) and let me know if it works for you.

**Comment by Aramus92** [comment] 2016-01-26 14:56
One strange thing was that I could just load the vessel in SPH to launch it. But now with this .dll it seems to work. Thank you!

**Comment by tscharlii** [comment] 2016-04-10 17:45
Thank you! I was experiencing the same issue and the replacement dll fixed it for me as well. Not including a save game here, but I started a fresh RP-0 Game and built "My first rocket" from https://github.com/KSP-RO/RP-0/wiki/Tutorial:-Getting-Started

**Comment by magico13** [comment] 2017-06-12 15:29
Since the dev builds appear to fix this, I'm going to close this (I'm doing some cleanup). If it comes up again, please let me know.

**Closed by magico13** 2017-06-12 15:29 UTC
